### ISSUE TITLE
home assistant update breaks connection with dimmer switch

### ISSUE THREAD

**Issue by wardcoertjens** [robmarkcole/Hue-sensors-HASS#134] opened 2019-04-24 20:46 UTC
Hi,

I recently updated my Hass.io instance from Home Assistant 0.86.3 to the latest 0.91.4. Since the update, my Hue dimmer switch does show up. All lights connected to the Hue bridge still work.
I already updated my custom_component files to the latest "huesensor" files, and updated my config, with no succes. Config shows no errors, and I can't seem to figure out where to fix it.

Any ideas where this could go wrong?

**Comment by Angstromboli** [comment] 2019-04-25 17:47
Hassio 0.88 had a major restructuring of how custom components need to be arranged. Perhaps you haven't put them in right. See this post about it: https://developers.home-assistant.io/blog/2019/02/19/the-great-migration.html

**Comment by robmarkcole** [comment] 2019-04-28 07:47
Duplicate of https://github.com/robmarkcole/Hue-sensors-HASS/issues/137

**Closed by robmarkcole** 2019-04-28 07:47 UTC
