### ISSUE TITLE
ha 0.88 custom updated doesn't see hue anymore

### ISSUE THREAD

**Issue by h4nc** [robmarkcole/Hue-sensors-HASS#118] opened 2019-02-21 11:25 UTC
Home assistant version 0.88 wants us to change from sensor/hue.py too hue/sensor.py

So I changed that and the component still works, but custom updater doesn't see the component any more.

**Comment by aptonline** [comment] 2019-02-21 12:18
The paths in ``custom_updater.json`` would need to be updated but as this component is unlikely to get updated for 0.88.0 (Rob is concentrating efforts on the official component, then it’s unlikely to be fixed.

**Comment by robmarkcole** [comment] 2019-02-21 12:20
Duplicate of https://github.com/robmarkcole/Hue-sensors-HASS/issues/117

**Closed by robmarkcole** 2019-02-21 12:20 UTC
