### ISSUE TITLE
Motion sensor no longer works

### ISSUE THREAD

**Issue by eFirewall** [robmarkcole/Hue-sensors-HASS#82] opened 2018-08-17 09:05 UTC
Hi,

I been using a hue motion sensor without problems for a month using Hassio as a platform.
Updated, without issues, to Home Assistant 0.75.3 and been using for a few days hassio 125 without issues (this is my current setup actually).

Today, after a reboot, the motion sensor no longer works.
I was using V0.6 and tried updating to V0.7 (currently installed) but the issue persisted.

This is what the log says:

```
2018-08-17 10:46:44 WARNING (MainThread) [homeassistant.loader] You are using a custom component for sensor.hue which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2018-08-17 10:46:44 WARNING (SyncWorker_7) [custom_components.sensor.hue] Cannot setup Hue sensors, check your config
```

I checked trough the python script to see what was detected:

```
>>> data
{'Geofence': {'name': 'FirePhone (2)', 'model': 'GEO', 'state': 'off'}, 'SML_b3-02': {'temperature': 26.27, 'model': 'SML', 'name': 'motion Habitacion', 'state': 'off', 'battery': 100, 'last_updated': ['2018-08-17', '08:02:29'], 'light_level': 17060, 'lux': 50.8, 'dark': True, 'daylight': False}}
>>> keys
['Geofence', 'SML_b3-02']
```

so far this is all. I don't know what can I do to fix this issue so, help would be appreciated.

**Comment by hvbhome** [comment] 2018-08-17 09:43
can you still see the motion sensor when using the Philips Hue Api directly?
Since the geofence is discovered, it seems the CC is working correctly, so it might be the Hub itself that isnt connecting to the sensor?

**Comment by eFirewall** [comment] 2018-08-17 09:47
Ok, I tried something else just for the shake of it and it worked.
I created a new API username, changed that in the config file and it works perfectly now.

**Comment by yottatsa** [comment] 2019-01-02 19:45
@eFirewall can't reproduce the issue, closing

**Closed by yottatsa** 2019-01-02 19:45 UTC
