### ISSUE TITLE
Roadmap to official release

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/Hue-sensors-HASS#107] opened 2019-01-19 06:09 UTC
As per [this thread](https://community.home-assistant.io/t/official-hue-sensors-component/76342/11), it would be nice to make this CC into an official HA component. This first requires resolution of [this issue](https://github.com/home-assistant/architecture/issues/128) about polling the Hue hub.

**Comment by robmarkcole** [comment] 2019-04-09 05:08
Watching https://github.com/home-assistant/home-assistant/pull/22598

**Comment by johansmitsnl** [comment] 2019-04-27 14:56
home-assistant/home-assistant#22598 got merged but it does not have remote support. Only sensor (light, motion and temperature).
A PR for the remotes would be great now with #85 in it.

**Closed** 2019-06-19 13:40 UTC

**Comment by johansmitsnl** [comment] 2019-06-19 23:08
What does it mean that the issue is closed?
Will this project continue?

**Comment by raoulteeuwen** [comment] 2019-06-20 04:40
Rob has stated before he has limited time for this project, especially currently, and any time he has, he wants to use to making HA support Hue natively. Anyone able to code can have a go at this custom component Hue code, and Rob will have a look at PR's, but other than that, we need to be grateful that he has made this code and hopefully will be able to keep it working 'as is' with HA-upgrades etc.

**Comment by johansmitsnl** [comment] 2019-06-20 12:22
@raoulteeuwen that is knew. But closing this issue sounds like official integration will not go forward to me.

I have a open pr to make the scan interval more frequently but it is blocked by the owners. That's why I asked before what the status was and how these scan intervals have been discussed with the ha owners. 

I would love to see the addition of the remotes but this will only work if the scan interval is lowered.
