### ISSUE TITLE
2.13 Multi Bridge scenario broken?

### ISSUE THREAD

**Issue by Kugelfang666** [robmarkcole/Hue-sensors-HASS#225] opened 2020-03-10 11:00 UTC
Couldn’t be that with 2.13 something broke for multi Bridge scenarios? I had all buttons from one bridge comming up whereas the remotes from the second bridge were all unavailable.

I moved from 2.12 to 2.13 on my HA 0.106.4

**Comment by azogue** [comment] 2020-03-10 11:40
> Couldn’t be that with 2.13 something broke for multi Bridge scenarios? 

It could be, sorry. I didn't test it for that (I only have 1). Could you provide log details? 

(set `custom_components.huesensor: debug` in `logger`)

**Comment by azogue** [comment] 2020-03-10 16:24
Hi @Kugelfang666,

could you share some more info?

Are both bridges configured with main hue integration in HA?

**Comment by ianfretwell** [comment] 2020-03-10 16:57
Just to add to this - I have two bridges, both with lamps, switches and sensors on each.  All of which are still working just fine for me with 2.13.

They are also configured with the main hue integration in HA (effectively I use the main integration for the lights and this custom component for everything else).

**Comment by Kugelfang666** [comment] 2020-03-10 19:41
I just checked, all entities of sensors/dimmers from the huesensor integration that are connected to my second bridge are not available. This persist a reboot. the moment I move back to 2.12 they all come back on. the only related error I saw is this:

`Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/huesensor/data_manager.py", line 137, in async_update_from_bridges
    self.sensors[dev_id].async_write_ha_state()
KeyError: 'RWL_XX:XX:XX:XX:XX:XX:XX:XX-XX'`

**Comment by azogue** [comment] 2020-03-10 19:53
Hi @Kugelfang666, I'm on it. Some questions:

- Error is happening continuously, right? (for each update)
- If setting logging level to debug, it should be 1 log entry for each configured sensor/remote, in HA setup. The keyerror is for a key that was configured previously, or it is a new one?

I'll push some changes in tests in #226 with some error handling for this, so we can try to debug and fix it, I'll ping you when done.

**Comment by Mariusthvdb** [comment] 2020-03-10 19:56
Well at least the error is consistent with the error I reported in the issue on binary sensors not being created

**Comment by Kugelfang666** [comment] 2020-03-10 19:57
hold on: I just realized something:

with 2.12. in the entities tab I find the motion sensors exposed all under the huesensor integration. 

with 2.12. I find some exposed under the huesensor integration and some as Philips Hue... is this expected? 

Naive question: does the stock hue integration expose motions sensors at all?

**Comment by azogue** [comment] 2020-03-10 20:03
> with 2.12. I find some exposed under the huesensor integration and some as Philips Hue... is this expected?

Are they duplicated, or are different sets?

Remotes should appear only under this CC, but

> Naive question: does the stock hue integration expose motions sensors at all?

Yes :), but it has a fixed scan_interval of 5 s, so unusable for automate motion. But, yes. In fact,
I suggest you to configure only remotes with the CC, and rely on the official motion sensors (after configuring the CC they will have the same high refresh rate). Or disable the official ones in the UI.

**Comment by Kugelfang666** [comment] 2020-03-10 20:16
yes, the remotes are only exposed under huesensor, 

for the sensors, with 2.12. every sensor is exposed twice (1x huesensor, 1x Philips Hue)
for 2.13. every sensors is exposed twice, but all sensors from my second bridge are unavailable under the huesensors CC

**Comment by Kugelfang666** [comment] 2020-03-10 20:17
and yes, the error showed up 16 times just a few seconds after a full reboot

**Comment by Mariusthvdb** [comment] 2020-03-10 20:18
> (after configuring the CC they will have the same high refresh rate).

Does this really make the core sensors update more frequently ? Which is what Balloob always states to be impacting HA negatively...

This might be  causing what Iam experiencing then, as stated in an other post: 2.13 makes Ha less responsive than 2.12...

**Comment by azogue** [comment] 2020-03-11 13:41
Hi @Kugelfang666, 

>  but all sensors from my second bridge are unavailable under the huesensors CC

Some things were broken (sorry!) with the refactor. I hope they are fixed with #229. Could you check it before it is released, to be sure?

**Comment by azogue** [comment] 2020-03-11 14:59
Hi @Mariusthvdb,

> Does this really make the core sensors update more frequently ? Which is what Balloob always states to be impacting HA negatively...

What he says about is **related to the hammering of the Hue bridge**, let me try to clarify some ideas for better understanding of the context:
- The **Hue bridge** is limited, and it can accept up to some maximum rate of requests. (**_we are talking about the Hue physical device, not related at all with the power of the HA host_**)
- When it gets stressed (like any other server), it starts to fail ~ramdomly, returning bad responses or just not responding to them (timeouts)
- To avoid those situations when possible, a lot of refined development has been done inside HA Core and also in the 'mother' async request library, `aiohue` (guess who's the author on that one too), to **minimize the number of requests to the bridge** (as you can get all the information in one request, and then share the response data)
- The fact that you **can see** errors and entities going unavailable in HA means some things:
  * It is telling you that HA is having problems calling the bridge at that moment
  * But that does not imply that the problem is in HA, **it implies that there is some stress in the Hue hub**, and that is a well-known issue caused by a lot of clients calling it at the same time.
- How many **clients**?
  * If you use Alexa/GHome/Homekit and have your hue lights in it, count one each.
  * Mobile Hue apps? sum another one each.
  * Any other hub/app/service with access to your lights: keep adding.
  * HomeAssistant: add another one from the official hue integration.
  * Any rest sensor, curl command, anything extra: more clients.
  * **This CC before v2.12, another client more, calling the bridge with 1 request/s** (yes, `scan_interval` of 0.1 or 0.5 secs does not mean 10Hz or 2Hz rates, time it)
- With so many clients, in big installations, the bridge is expected to fail some times, and **that is not HA fault**: in most of those cases, if you see the behavior in other clients (like the iOS home app), you will see those disconnections too. But these are normally undetected, and with HA you see all of them :)

Within that context, this CC was, just by itself, a big consumer and stress creator for the bridges, and that is why @balloob advises against using it (and also shows another route to obtain pushing behavior of these devices).

What we did in last refactor was to remove the extra client on this CC, and rely on the debounced and shared client of the hue integration.

What that means in practice is, if before that there were 2 clients calling the hub (1Hz for CC, ~0.5Hz for HA), that was a total of 15 calls each 10sec from 2 clients (without anything more).
After the refactor, the same scenario has 10 calls / 10 sec from 1 client.
(reality is more complex, but I think the numeric example is valid to show the concept here)

This change has some consecuences:
- As the sensor data coordinator is the same, and this CC imposes (by default) a refresh update of 1Hz, each update is going to trigger the state update of each linked entity (all sensors added with the official hue integration).
- **This 'collateral' benefit should not make HA less responsive**. In fact it is the opposite, for the added sensors there. Hue errors and light/sensor unavailability come from issues in the bridges, not in HA (unless there is some bug, which is always a possibility, of course)

> Couldn’t you make custom integration not interfering with core Hue?

I hope I explained why the ongoing direction is actually the opposite.

But let's do a thought experiment:
- Let's say 1Hz is too slow and you want to ask the bridge with 10Hz, or 20Hz,
- Take the CC before the refactor, which was already using the same async library `aiohue` than the official integration.
- Remove the use of async_track_interval, as it is not going to call update with more than > 1Hz, use asyncio.wait(0.05) instead to wait between calls and go sub-second.
- Add all imaginable error handling to forget about any faulty request, just relying on the next valid one.

With those changes you'll have a super-fast response, without any interaction with HA**, no worrying logs, and almost like a _pushing_ behavior.

** But what we just invented is a DDOS-like attacker to the hue bridge, which will be trashing it constantly, and any other Hue client will be showing issues, including of course HA, which will be logging everything :)

The efforts going on in HA Core (and also in the changes here) are in the direction to optimize the number of calls to the bridges, trying to minimize issues that are usually created by other clients, and that is **why is so important to isolate the real hue issues in HA**, and require any issue to be sure that no other client is interfering.

**Closed** 2020-03-11 15:53 UTC
